// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeB7om2wyP0TBDXOQ3LNesPUsgEugWow8',
    appId: '1:205824602388:web:92662de59baf8c069a9201',
    messagingSenderId: '205824602388',
    projectId: 'mediapp-75e55',
    authDomain: 'mediapp-75e55.firebaseapp.com',
    storageBucket: 'mediapp-75e55.appspot.com',
    measurementId: 'G-Y22R3KJ5DZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuAPrIjO4AVP45FQkLCh2s6MPpChOQou0',
    appId: '1:205824602388:android:c9aa3c1151dd9e909a9201',
    messagingSenderId: '205824602388',
    projectId: 'mediapp-75e55',
    storageBucket: 'mediapp-75e55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPBTPmhMSX9OEsN2Sa5TTVjP092H7yMg4',
    appId: '1:205824602388:ios:b9875af67f28a1b39a9201',
    messagingSenderId: '205824602388',
    projectId: 'mediapp-75e55',
    storageBucket: 'mediapp-75e55.appspot.com',
    iosBundleId: 'com.example.doctorQppointmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPBTPmhMSX9OEsN2Sa5TTVjP092H7yMg4',
    appId: '1:205824602388:ios:c100e7a87ea9ed1b9a9201',
    messagingSenderId: '205824602388',
    projectId: 'mediapp-75e55',
    storageBucket: 'mediapp-75e55.appspot.com',
    iosBundleId: 'com.example.doctorQppointmentApp.RunnerTests',
  );
}
